### PR TITLE
Added lad1.jar

### PR DESCRIPTION
**Pull request by VladSnegovsky**
In few days will add ready-made tests.

### CODE REVIEW

**Comment by dt-iss** [comment]
What type of cancelation you implemented? Which key combination should be used for cancelation?

**Comment by VladSnegovsky** [comment]
> What type of cancelation you implemented? Which key combination should be used for cancelation?

Added key Combination

**Comment by dt-iss** [comment]
Where do you use Java monitors?

**Comment by VladSnegovsky** [comment]
> Where do you use Java monitors?

Done
In Function 1/2

**Comment by dt-iss** [comment]
You should implement functions f(x) and g(x) for all 6 test cases (see section Testing in the task description). You don't need to write unit tests, because it wasn't required in the task.

**Comment by VladSnegovsky** [comment]
> You should implement functions f(x) and g(x) for all 6 test cases (see section Testing in the task description). You don't need to write unit tests, because it wasn't required in the task.

Done

**Review by dt-iss — APPROVED** [review]

**Pull request merged**
